/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tawjihiPackage;

import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class gradesInserting extends javax.swing.JFrame {

    /**
     * Creates new form gradesInserting
     */
    public gradesInserting() {
        initComponents();
               urlCombo.removeAllItems();
   /*    urlCombo.addItem("http://localhost/Networks2HWS/phpTawjihi/tawjihi.php");
  
        urlCombo.addItem("http://localhost:8084/servletProject0/tawjihi");
        urlCombo.addItem("http://localhost/Networks2HWS/PhpProject3/index.php");*/
   
   urlCombo.addItem("Servlet server");
   urlCombo.addItem("PHP server");
   urlCombo.addItem("JSP server");
   
   CityCombo.removeAllItems();
   CityCombo.addItem("Jerusalem");
   CityCombo.addItem("Nablus");
   CityCombo.addItem("Hebron");
   CityCombo.addItem("Ramallah");
   CityCombo.addItem("Tulkarm");
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        urlCombo = new javax.swing.JComboBox<>();
        insertPost = new javax.swing.JButton();
        back = new javax.swing.JButton();
        InsertGET = new javax.swing.JButton();
        grade = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        CityCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        urlCombo.setBackground(new java.awt.Color(153, 153, 255));
        urlCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        insertPost.setBackground(java.awt.Color.white);
        insertPost.setText("Insert Post");
        insertPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPostActionPerformed(evt);
            }
        });

        back.setBackground(java.awt.Color.white);
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        InsertGET.setBackground(java.awt.Color.white);
        InsertGET.setText("Insert Get");
        InsertGET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertGETActionPerformed(evt);
            }
        });

        grade.setText("grade");
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });

        name.setText("Name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        CityCombo.setBackground(new java.awt.Color(153, 153, 255));
        CityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(InsertGET, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(insertPost, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(urlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(urlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertPost, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertGET, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPostActionPerformed
       Insert_Post();
      
    }//GEN-LAST:event_insertPostActionPerformed

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Sign f=new Sign();
        f.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void InsertGETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertGETActionPerformed
       insert_Get();
       
    }//GEN-LAST:event_InsertGETActionPerformed
  String dataStr = "";
 
    String contentStr = "application/x-www-form-urlencoded";

    public void addParameter(String ps, String vs) {
        if (ps == null || vs == null || ps.length() == 0 || vs.length() == 0) {
            return;
        }
        if (dataStr.length() > 0) {
            dataStr += "&";
        }
        try {
            dataStr += ps + "=" + URLEncoder.encode(vs, "ASCII");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    void  Insert_Post() {
        
        dataStr = "";
        OutputStream os;
        InputStream is;
       
     System.out.println(" inside post beggining");
          String city=CityCombo.getSelectedItem().toString();
          int gradeInt=Integer.parseInt(this.grade.getText());
          if(gradeInt<0 || gradeInt>100)
          {
            JOptionPane.showMessageDialog(this,"Wrong grade value ,insert again");  
            return;
          }
          String gradeString=this.grade.getText();
           String name=this.name.getText();
        addParameter("name", name); 
        addParameter("grade", gradeString); 
         addParameter("city", city); 
        String urlStr=null; ;
          
           if(urlCombo.getSelectedIndex()==0)
               urlStr="http://localhost:8084/servletProject0/insert";
           else if(urlCombo.getSelectedIndex()==1)
                urlStr="http://localhost/Networks2HWS/PhpProject3/insert.php";
            else if(urlCombo.getSelectedIndex()==2)
                  urlStr="http://localhost:8084/servletProject0/insert.jsp";
 
                
        try {
            URL myURL = new URL(urlStr);
            URLConnection myConn = myURL.openConnection();
            
            myConn.setDoOutput(true);
            myConn.setDoInput(true);
            myConn.setRequestProperty("Content-Type", contentStr);
            myConn.setUseCaches(false);
            //dataStr = "T1=67&T2=88";
          
            BufferedOutputStream out = new BufferedOutputStream(myConn.getOutputStream());
            out.write(dataStr.getBytes());//"ACTION=add&NUMPTS=2&DATA=L0001\nL0002");
            out.close();

            //out.close();
            String SS = "";
            int b = -1;

            String t = "";
            is = myConn.getInputStream();
            System.out.println(" inside get end");
            while ((b = is.read()) != -1) {
               
                    SS = SS + (char) b;
                };
      
           
            }
          
            
         catch (Exception e) {
            System.out.println(e.toString());
          
        }

    }
     void insert_Get() {
        DataInputStream dis;
         String urlStr=null; ;
         System.out.println(" inside get beggining");
           if(urlCombo.getSelectedIndex()==0)
               urlStr="http://localhost:8084/servletProject0/insert";
           else if(urlCombo.getSelectedIndex()==1)
                urlStr="http://localhost/Networks2HWS/PhpProject3/insert.php";
           else if(urlCombo.getSelectedIndex()==2)
                 urlStr="http://localhost:8084/servletProject0/insert.jsp";
           
  /*    urlCombo.addItem("http://localhost/Networks2HWS/phpTawjihi/tawjihi.php");
  
        urlCombo.addItem("http://localhost:8084/servletProject0/tawjihi");
        urlCombo.addItem("http://localhost/Networks2HWS/PhpProject3/index.php");*/
        try {
          
          String city=this.CityCombo.getSelectedItem().toString();
          int gradeInt=Integer.parseInt(this.grade.getText());
           if(gradeInt<0 || gradeInt>100)
          {
            JOptionPane.showMessageDialog(this,"Wrong grade value ,insert again");  
            return;
          }
          String gradeString=this.grade.getText();
           String name=this.name.getText();
            String str = urlStr+ "?name=" +name+"&grade="+gradeString+"&city="+city;
            
            URL u = new URL(str);
          //  this.URLtextf.setText("GET: sending to " + str);
            System.out.println(" inside get end");
            dis = new DataInputStream(u.openConnection().getInputStream());
           
            int b;
            String t = "";
            String SS = "";

            URLConnection myConn = u.openConnection();
            InputStream is = myConn.getInputStream();
            
            
           ///new
         
            while ((b = is.read()) != -1) {
              
                    SS = SS + (char) b;
               

            }
       
          

        } catch (Exception e) {
            System.out.println(e.toString());
           
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gradesInserting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gradesInserting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gradesInserting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gradesInserting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gradesInserting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CityCombo;
    private javax.swing.JButton InsertGET;
    private javax.swing.JButton back;
    private javax.swing.JTextField grade;
    private javax.swing.JButton insertPost;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> urlCombo;
    // End of variables declaration//GEN-END:variables
}
